'use strict';
/**
 * OpenPersona - Porter export security tests
 *
 * Ensures exportPersona respects the pack .gitignore and does NOT bundle
 * sensitive runtime files (acn-registration.json, state.json, handoff.json,
 * soul/self-narrative.md, social/contacts.json, social/contacts.jsonl,
 * social/.poller-cursor.json).
 *
 * social/contacts.json is gitignored because it accumulates private relationship
 * data (notes, trust ratings, interaction history). It is re-materialized from
 * persona.json.social.contacts.seed on install/import (see lib/lifecycle/installer.js).
 *
 *  1. exportPersona does not include acn-registration.json
 *  2. exportPersona does not include state.json
 *  3. exportPersona does not include handoff.json
 *  4. exportPersona does not include soul/self-narrative.md
 *  5. exportPersona does not include social/contacts.jsonl
 *  6. exportPersona does not include social/.poller-cursor.json
 *  7. exportPersona does NOT include social/contacts.json (private runtime data)
 *  8. exportPersona DOES include persona.json
 *  9. exportPersona DOES include agent-card.json
 * 10. exportPersona with no .gitignore still works (no crash)
 */

const { describe, it, before, after } = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('fs-extra');
const os = require('node:os');
const AdmZip = require('adm-zip');

const { exportPersona } = require('../lib/lifecycle/porter');

describe('porter export security', () => {
  let packDir;
  let zipPath;

  before(async () => {
    packDir = await fs.mkdtemp(path.join(os.tmpdir(), 'op-porter-security-'));

    // Simulate a generated persona pack
    await fs.writeFile(path.join(packDir, 'persona.json'), JSON.stringify({ slug: 'porter-test' }));
    await fs.writeFile(path.join(packDir, 'SKILL.md'), '# Porter Test');
    await fs.writeFile(path.join(packDir, 'agent-card.json'), JSON.stringify({ name: 'PorterTest' }));

    // Runtime files (should be excluded)
    await fs.writeFile(path.join(packDir, 'acn-registration.json'), JSON.stringify({ agent_id: 'secret', api_key: 'sk-secret' }));
    await fs.writeFile(path.join(packDir, 'state.json'), JSON.stringify({ mood: 'happy' }));
    await fs.writeFile(path.join(packDir, 'handoff.json'), JSON.stringify({ context: 'secret handoff' }));

    // Soul runtime files
    await fs.ensureDir(path.join(packDir, 'soul'));
    await fs.writeFile(path.join(packDir, 'soul', 'self-narrative.md'), '# Secret narrative');
    await fs.writeFile(path.join(packDir, 'soul', 'persona.md'), '# Soul file (safe to export)');

    // Social files
    await fs.ensureDir(path.join(packDir, 'social'));
    await fs.writeFile(
      path.join(packDir, 'social', 'contacts.json'),
      JSON.stringify({ schemaVersion: '1.0.0', personaSlug: 'porter-test', contacts: [] })
    );
    await fs.writeFile(path.join(packDir, 'social', 'contacts.jsonl'), '{"event":"old"}\n');
    await fs.writeFile(path.join(packDir, 'social', '.poller-cursor.json'), '{"cursor":"old"}');

    // .gitignore — same as generated by generator/index.js
    await fs.writeFile(path.join(packDir, '.gitignore'), [
      '# OpenPersona runtime files — do not commit to version control',
      'acn-registration.json',
      'state.json',
      'handoff.json',
      'soul/self-narrative.md',
      '# Social Contacts runtime files (private relationship data — never export)',
      'social/contacts.json',
      'social/contacts.jsonl',
      'social/.poller-cursor.json',
      '',
    ].join('\n'));

    zipPath = path.join(os.tmpdir(), `porter-security-test-${Date.now()}.zip`);
    exportPersona(packDir, zipPath);
  });

  after(async () => {
    await fs.remove(packDir);
    if (fs.existsSync(zipPath)) fs.unlinkSync(zipPath);
  });

  function getZipEntryNames() {
    const zip = new AdmZip(zipPath);
    return zip.getEntries().map((e) => e.entryName);
  }

  it('does not include acn-registration.json', () => {
    const entries = getZipEntryNames();
    assert.ok(!entries.some((e) => e.includes('acn-registration.json')),
      `acn-registration.json must not be in zip. Found: ${JSON.stringify(entries)}`);
  });

  it('does not include state.json', () => {
    assert.ok(!getZipEntryNames().some((e) => e === 'state.json'));
  });

  it('does not include handoff.json', () => {
    assert.ok(!getZipEntryNames().some((e) => e === 'handoff.json'));
  });

  it('does not include soul/self-narrative.md', () => {
    const entries = getZipEntryNames();
    assert.ok(!entries.some((e) => e.includes('self-narrative.md')),
      `soul/self-narrative.md must not be in zip. Found: ${JSON.stringify(entries)}`);
  });

  it('does not include social/contacts.jsonl', () => {
    const entries = getZipEntryNames();
    assert.ok(!entries.some((e) => e.includes('contacts.jsonl')),
      `social/contacts.jsonl must not be in zip. Found: ${JSON.stringify(entries)}`);
  });

  it('does not include social/.poller-cursor.json', () => {
    const entries = getZipEntryNames();
    assert.ok(!entries.some((e) => e.includes('.poller-cursor.json')),
      `.poller-cursor.json must not be in zip. Found: ${JSON.stringify(entries)}`);
  });

  it('does NOT include social/contacts.json (private runtime relationship data)', () => {
    const entries = getZipEntryNames();
    assert.ok(!entries.some((e) => e.includes('contacts.json')),
      `social/contacts.json must not be in zip (private runtime data). Found: ${JSON.stringify(entries)}`);
  });

  it('DOES include persona.json', () => {
    const entries = getZipEntryNames();
    assert.ok(entries.some((e) => e === 'persona.json'),
      `persona.json must be in zip. Entries: ${JSON.stringify(entries)}`);
  });

  it('DOES include agent-card.json', () => {
    const entries = getZipEntryNames();
    assert.ok(entries.some((e) => e === 'agent-card.json'),
      `agent-card.json must be in zip. Entries: ${JSON.stringify(entries)}`);
  });

  it('exportPersona with no .gitignore does not crash', async () => {
    const emptyDir = await fs.mkdtemp(path.join(os.tmpdir(), 'op-porter-no-gitignore-'));
    try {
      await fs.writeFile(path.join(emptyDir, 'persona.json'), JSON.stringify({ slug: 'no-gi' }));
      const out = path.join(os.tmpdir(), `no-gitignore-${Date.now()}.zip`);
      assert.doesNotThrow(() => exportPersona(emptyDir, out));
      if (fs.existsSync(out)) fs.unlinkSync(out);
    } finally {
      await fs.remove(emptyDir);
    }
  });
});
